
---
apiVersion: v1
kind: Namespace
metadata:
  name: micro
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: micro
  name: mongodb-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
      - name: mongodb
        image: mongo:latest
        ports:
        - containerPort: 27017
        env:
          - name: MONGO_INITDB_ROOT_USERNAME
            value: "movieadmin"
          - name: MONGO_INITDB_ROOT_PASSWORD
            value: "movie123"
          - name: MONGO_INITDB_DATABASE
            value: "moviedb"
---
apiVersion: v1
kind: Service
metadata:
  namespace: micro
  name: mongodb-service
spec:
  selector:
    app: mongodb
  ports:
  - protocol: TCP
    port: 27017
    targetPort: 27017
  type: ClusterIP

